# Site settings
title: 星辰大海
header-img: "img/autumn2.jpg"
tagline: "星辰大海"  
description: "勿忘初心"  
baseurl: ""
url: "http://sqq5682.github.io"  
#url: "http://localhost:4000"

# About/contact
owner: 
  name: "星辰大海"
  email: sqq5682@126.cn
  bio: "勿忘初心"
  bjRecord: "京公网安备 11010502043471号"
  hnRecord: "豫ICP备2020035902号"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.ico

douban_username: sqq5682
twitter_username:  
github_username: sqq5682  
facebook_username:  
weibo_username:  
zhihu_username: song-qiang-qiang  

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments

gems: [jekyll-paginate]
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Beijing

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "sqq5682"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : sqq5682
  disqus :
      short_name : sqq5682

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
#9、IntenseDebate
intensedebate_comments: true